version: '3.9'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1521:1521"  # Porta do banco de dados Oracle
      - "5500:5500"  # Porta para Oracle EM Express
    environment:
      - ORACLE_PWD=UserAdmin123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8081:8978"  # Expondo a interface web do DBeaver
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace
    environment:
      - CB_ADMIN_NAME=UserAdmin
      - CB_ADMIN_PASSWORD=UserAdmin123
    restart: unless-stopped

volumes:
  oracle-data:
  dbeaver-data:
